services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
